<#
PowerShell helper: setup-env.ps1
- Base64-encodes a Firebase service account JSON and writes it to `.env.local` (or `.env`) as FIREBASE_SERVICE_ACCOUNT_BASE64
- Optionally writes common FIREBASE_* variables to `.env.local`
- Optionally creates/updates the env var in Vercel via the Vercel API if you provide `-VercelToken` and `-VercelProject` (project slug)

Usage examples:
# Only prepare local .env.local using service-account.json in repo root
pwsh .\scripts\setup-env.ps1 -ServiceAccountPath .\service-account.json

# Provide firebase client keys as well
pwsh .\scripts\setup-env.ps1 -ServiceAccountPath .\service-account.json -FirebaseApiKey 'API_KEY' -FirebaseAuthDomain 'your-app.firebaseapp.com' -FirebaseProjectId 'your-project-id' -FirebaseAppId '1:...' 

# Also push to Vercel (requires Vercel personal token and project slug)
pwsh .\scripts\setup-env.ps1 -ServiceAccountPath .\service-account.json -VercelToken '<YOUR_TOKEN>' -VercelProject 'your-project-slug'
# Note: Vercel token must have project write permissions. This will create the env var for production, preview and development targets.
#
# Security: Keep service-account.json private. This script will NOT upload raw JSON to remote providers unless you explicitly provide a Vercel token.
#>

param(
  [string]$ServiceAccountPath = '.\service-account.json',
  [string]$OutEnvPath = '.env.local',
  [string]$FirebaseApiKey = '',
  [string]$FirebaseAuthDomain = '',
  [string]$FirebaseProjectId = '',
  [string]$FirebaseAppId = '',
  [string]$VercelToken = '',
  [string]$VercelProject = ''
)

function Write-Log($m){ Write-Host "[setup-env] $m" }

if(-not (Test-Path $ServiceAccountPath)){
  Write-Log "Service account file not found at '$ServiceAccountPath'"
  Write-Log "Please place your Firebase service-account.json at that path or pass -ServiceAccountPath"
  exit 1
}

try{
  $json = Get-Content $ServiceAccountPath -Raw -ErrorAction Stop
}catch{
  Write-Log "Failed to read service account: $_"
  exit 1
}

try{
  $b64 = [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($json))
}catch{
  Write-Log "Base64 encode failed: $_"
  exit 1
}

# Prepare .env.local contents (append/overwrite safe keys)
$envLines = @()
$envLines += "# Generated by scripts/setup-env.ps1 on $(Get-Date -Format o)"
$envLines += "FIREBASE_SERVICE_ACCOUNT_BASE64=$b64"
if($FirebaseApiKey -ne ''){ $envLines += "FIREBASE_API_KEY=$FirebaseApiKey" }
if($FirebaseAuthDomain -ne ''){ $envLines += "FIREBASE_AUTH_DOMAIN=$FirebaseAuthDomain" }
if($FirebaseProjectId -ne ''){ $envLines += "FIREBASE_PROJECT_ID=$FirebaseProjectId" }
if($FirebaseAppId -ne ''){ $envLines += "FIREBASE_APP_ID=$FirebaseAppId" }

try{
  $envContent = ($envLines -join "`n") + "`n"
  Set-Content -Path $OutEnvPath -Value $envContent -Encoding UTF8
  Write-Log "Wrote environment file to '$OutEnvPath' (contains FIREBASE_SERVICE_ACCOUNT_BASE64 and any provided FIREBASE_* vars)"
}catch{
  Write-Log "Failed to write $OutEnvPath: $_"
  exit 1
}

if($VercelToken -and $VercelProject){
  Write-Log "Vercel token and project provided — attempting to create/update env var via Vercel API"
  $url = "https://api.vercel.com/v9/projects/$VercelProject/env"
  $body = @{ key = 'FIREBASE_SERVICE_ACCOUNT_BASE64'; value = $b64; target = @('production','preview','development'); type = 'encrypted' } | ConvertTo-Json -Depth 5
  try{
    $r = Invoke-RestMethod -Method Post -Uri $url -Headers @{ Authorization = "Bearer $VercelToken"; 'Content-Type' = 'application/json' } -Body $body -ErrorAction Stop
    Write-Log "Vercel API response: $(($r | ConvertTo-Json -Depth 2))"
    Write-Log "If the environment variable already existed, you may need to remove duplicates from the Vercel dashboard."
  }catch{
    Write-Log "Vercel API request failed: $_"
    Write-Log "You can alternatively add the var manually in Vercel Project Settings → Environment Variables."
  }
}else{
  Write-Log "Vercel token or project not provided — skipped remote push. To push automatically provide -VercelToken and -VercelProject"
}

Write-Log "Done. Next steps:"
Write-Host "- If not already done, publish Firestore rules to allow reads and authenticated creates for /chats (see Firebase Console → Firestore → Rules)." -ForegroundColor Yellow
Write-Host "- If you updated env on Vercel, redeploy the project (push commit or trigger redeploy from Vercel dashboard)." -ForegroundColor Yellow
Write-Host "- After deployment, open your Vercel URL, sign in and try sending a chat message. Check DevTools Console for any permission errors." -ForegroundColor Yellow

exit 0
